gem:
  http:
    logging:
      enabled: true

logging:
  level:
    root: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude:
          - "/swagger-ui.html"
          - "/v3/api-docs"
          - "/actuator/**"
          - "/actuator/health"
          - "/actuator/prometheus"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
