gem:
  http:
    logging:
      enabled: true

logging:
  level:
    root: DEBUG

management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.50, 0.90, 0.99, 0.999
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
